# Instructions

1. Download the provided jupyter notebook file to your computer.
2. Write all your answers and code into this notebook file.
3. When your work is completed, export your notebook to an HTML file.
4. Submit your HTML file and a copy of the notebook to the assignment page on Moodle.

## Identification

### Your Information

Your Last Name:

Your First Name:


### Group Members (list any classmates you worked with on this problem set)

Your Group Members:

# Textbook Reading

The textbook readings for this week develop the theory of PCA in more detail and also introduce clustering methods. 

1. ISLP - Chapter 12.You should read section 12.1 which provides a general overview of the unsupervised learning problem. Sections 12.2 presents more of the underlying maths and theory of PCA, while Section 12.3 discussions an application to missing data. You may skim these sections if you find them interesting, but the technical detail will be outside the scope of our course. You should read section 12.4 in its entirety.  
2. Géron - Chapter 9. This chapter covers a wide range of unsupervised learning techniques. We will focus on a subst of the algorithms presented in the K-Means section. You may also wish to skim the section on DBSCAN, which is a useful algorithm for non-spherical clusters.

# Additional Reading - Applying AI to Rebuild Middle Class Jobs

Read the additional provided NBER Working Paper from David Autor - "Applying AI to Rebuild Middle Class Jobs". After reading the article, answer the following questions.

## Comparison to Acemoglu and Johnson Piece from Last Week

Both this piece and the Acemoglu and Johnson reading from last week evaluate the expected potential impact of AI on job availability and the potential for worker displacement. In what ways are the arguments of these articles similar? In what ways are they different?

_Your answer here:_

## The Role of Demographic Shifts

Autor often talks about the interaction between the growth in AI and demographic changes. Explain what the discussed demographic changes are and why they are important in this evaluation.

_Your answer here:_

## AI as an Inversion Technology

Autor discusses the current development of AI as an "inversion technology" relative to pre-AI computing. Explain what is meant by this and why this distinction is important for the paper's argument.

_Your answer here:_

# Additional OPTIONAL Reading - Efficiency of the EU regulation on greenhouse gas emissions in Italy

The problem set folder also provided the following additional reading:

Arbolino, Roberta, et al. "Efficiency of the EU regulation on greenhouse gas emissions in Italy: The hierarchical cluster analysis approach." Ecological Indicators 81 (2017): 115-123.

In this article the authors use a mix of PCA and hierarchical clustering to analyze the degree to which EU level regulatory decisions are implemented locally. As you read the article, think about how both clusters are identified but also how the authors evaluate and contextualize the identified clusters ex-post.

# Clustering on OECD Dataset

The provided `oecd_regional_wellbeing.csv` contains data from the OECD on Regional Well-Being measures. The full documentation for this data is available at this [link](https://www.oecdregionalwellbeing.org/).

The full dataset includes information by sub-national regions, but the provided data only contains information aggregated to the country-level. 

The goal of this problem is to allow you to practice clustering techniques on this data to see if we can arrive at measures of which countries are similar / dissimilar on these measure.

I have provided a copy of the data to you which mirrors what you would download from the OECD website and I have not in general cleaned the data in any special way. You may need to clean the data and decide how you want to handle any missing values.

Note: Throughout this problem you may use `random_state=0` to make your code replicable.

In [7]:
import pandas as pd
import numpy as np

from sklearn.cluster import KMeans

# Plotting
# from lets_plot import *
# LetsPlot.setup_html()

# Additional packages for later interactive displays
from ipywidgets import interact, IntSlider, Dropdown, fixed

In [5]:
oecd = pd.read_csv('oecd_regional_wellbeing.csv', encoding='latin-1')
oecd

,country,countrycode,Disposable income per capita,Employment rate,Unemployment rate,Homicide rate,Life expectancy,Population with at least secondary education,Number of rooms per capita,Mortality rate,Voter turnout,Households broadband access,Air quality (PM2.5),Life satisfaction,Satisfaction with housing affordability,Internet speed,Perceived social network support
0,Australia,AUS,39 872,76.3,4.1,0.9,83.0,15.3,2.3,3.0,89.8,86.1,8.5,7.1,41.6,-44.8,92.4
1,Austria,AUT,37 640,75.5,4.8,0.7,81.9,13.8,1.8,8.6,75.6,91.0,11.1,7.0,59.9,-42.5,89.8
2,Belgium,BEL,35 487,62.8,5.8,1.4,82.3,17.2,2.1,8.6,90.7,94.6,11.8,6.9,59.3,-16.3,89.9
3,Canada,CAN,32 387,72.2,6.1,1.9,81.3,6.9,2.5,6.3,62.2,93.3,12.7,7.0,38.8,22.4,91.9
4,Chile,CHL,8 261,62.9,8.7,4.5,81.0,17.6,1.3,9.9,46.7,75.2,23.1,6.2,28.7,49.4,87.3
5,Colombia,COL,NaN,59.8,11.5,25.5,76.8,36.8,1.0,9.3,60.4,48.4,13.5,5.8,46.6,-18.9,80.4
6,Costa Rica,CRI,10 470,71.5,7.3,17.2,80.9,58.6,1.1,6.8,60.7,80.1,8.7,6.8,55.0,-41.0,33.2
7,Czechia,CZE,26 092,75.1,2.3,1.5,79.9,5.7,1.5,10.2,65.4,92.8,13.0,6.8,50.7,-41.9,93.7
8,Denmark,DNK,27 796,76.8,5.3,0.8,81.8,16.4,1.9,8.9,84.2,92.5,9.2,7.6,71.3,7.6,94.6
9,Estonia,EST,17 711,74.4,7.9,1.7,79.0,11.2,1.6,10.3,63.5,90.9,9.1,6.4,62.8,-46.7,93.6
10,Finland,FIN,28 154,72.2,9.4,1.1,81.6,11.1,1.8,9.0,66.8,95.5,7.1,7.8,75.2,-13.1,95.6
11,France,FRA,30 656,65.0,7.6,1.2,83.0,16.1,1.8,8.0,77.8,88.1,10.7,6.7,47.9,46.3,87.4
12,Germany,DEU,35 532,76.2,8.2,0.8,81.1,16.2,1.8,13.4,82.5,88.8,11.6,6.9,55.8,-34.9,89.1
13,Greece,GRC,20 931,70.9,12.9,0.7,81.8,17.9,1.3,9.1,53.7,85.0,11.1,5.9,40.4,-56.2,84.1
14,Hungary,HUN,21 024,73.8,4.4,0.7,76.5,11.9,1.6,12.8,69.7,94.8,12.5,6.1,44.8,3.9,94.2
15,Iceland,ISL,30 704,84.9,3.6,1.3,82.4,17.5,1.5,8.4,66.9,94.9,6.5,NaN,NaN,33.5,97.7
16,Ireland,IRL,29 853,75.1,4.5,0.7,82.9,10.6,2.0,8.2,59.7,93.5,7.5,7.0,42.5,-9.2,91.6
17,Israel,ISR,15 120,69.7,3.7,1.5,82.6,12.4,1.2,7.5,68.5,74.3,20.6,7.3,29.7,27.7,93.5
18,Italy,ITA,31 920,61.9,7.5,0.6,83.4,33.3,1.5,7.9,63.9,84.1,15.8,6.4,56.3,-9.0,86.2
19,Japan,JPN,22 891,73.3,2.7,0.7,84.7,5.4,1.8,7.2,56.0,71.7,17.2,6.0,80.6,8.6,87.7
20,Korea,KOR,25 303,62.0,2.7,1.1,83.5,6.4,1.6,6.8,66.2,99.9,30.1,6.0,61.8,6.0,79.6
21,Latvia,LVA,15 293,70.1,8.4,4.3,75.5,9.1,1.2,12.7,59.4,94.3,10.4,6.2,46.6,-29.0,91.9
22,Lithuania,LTU,17 929,72.5,6.8,2.6,77.4,5.6,1.6,11.4,52.2,90.4,9.8,6.6,45.9,-14.7,84.9
23,Luxembourg,LUX,45 344,68.2,6.6,1.4,83.4,17.6,2.0,7.9,87.2,97.4,10.5,7.2,45.3,4.5,88.7
24,Mexico,MEX,8 358,63.9,2.7,24.2,75.5,56.1,1.5,11.8,61.0,75.6,14.6,6.5,50.3,-54.0,82.2
25,Netherlands,NLD,31 827,84.3,3.9,0.6,81.9,19.2,2.1,8.9,81.6,98.6,12.1,7.4,41.2,13.9,92.7
26,New Zealand,NZL,25 124,78.4,3.6,0.9,81.8,19.1,2.4,8.4,78.2,NaN,6.7,7.1,34.4,-12.5,94.5
27,Norway,NOR,32 368,77.4,3.7,0.7,83.1,16.3,2.3,8.1,77.1,98.6,6.8,7.4,55.4,-10.1,93.9
28,Poland,POL,24 597,76.6,3.1,1.4,78.4,5.2,1.4,11.1,74.4,95.0,13.5,6.3,33.9,2.0,88.6
29,Portugal,PRT,26 467,72.6,6.2,0.7,81.2,38.5,2.0,8.4,59.8,87.0,10.5,6.0,34.7,5.2,87.3
30,Slovak Republic,SVK,20 282,76.0,5.4,1.1,78.2,6.1,1.1,11.2,68.5,90.5,10.9,6.3,52.1,-27.0,93.8
31,Slovenia,SVN,27 250,73.1,3.7,0.3,82.0,11.0,1.6,8.7,53.6,94.0,13.5,6.7,28.5,-27.9,93.9
32,Spain,ESP,26 156,61.3,12.7,0.7,83.8,35.1,2.0,7.6,66.6,96.8,9.7,6.4,42.5,11.0,92.9
33,Sweden,SWE,30 943,77.4,8.5,1.1,83.4,11.3,1.8,7.9,87.1,100.0,6.8,7.3,55.1,-14.1,93.5
34,Switzerland,CHE,64 469,83.9,4.2,0.6,84.3,13.8,1.8,7.3,45.1,98.1,12.5,7.3,59.6,29.7,92.2
35,Türkiye,TUR,NaN,70.9,12.1,2.5,77.3,52.4,1.5,11.2,88.9,96.4,14.5,4.9,27.1,-52.5,80.2
36,United Kingdom,GBR,33 222,78.5,3.6,0.9,80.7,17.8,2.0,9.2,60.3,99.8,9.2,6.8,46.2,-9.9,89.2
37,United States,USA,59 961,76.6,3.7,5.9,77.0,9.7,2.4,10.0,65.3,86.4,12.7,6.8,51.4,29.0,89.1
38,Bulgaria,BGR,17 805,70.8,4.5,1.1,75.8,13.1,1.3,13.2,33.0,83.5,9.6,5.4,64.8,-41.8,NaN
39,Croatia,HRV,20 013,68.2,5.1,0.7,78.6,9.7,1.2,11.3,NaN,86.1,12.4,6.0,47.5,-25.7,NaN
40,Romania,ROU,19 865,63.8,5.7,0.7,76.4,19.8,1.1,12.7,31.9,88.2,10.7,6.5,45.5,6.2,NaN

In [13]:
oecd_clean = oecd.dropna()
oecd_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 34 entries, 0 to 37
Data columns (total 17 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   country                                       34 non-null     object
 1   countrycode                                   34 non-null     object
 2   Disposable income per capita                  34 non-null     object
 3   Employment rate                               34 non-null     float64
 4   Unemployment rate                             34 non-null     float64
 5   Homicide rate                                 34 non-null     float64
 6   Life expectancy                               34 non-null     float64
 7   Population with at least secondary education  34 non-null     float64
 8   Number of rooms per capita                    34 non-null     float64
 9   Mortality rate                                34 non-null     float64
 10  Voter turnout                                 34 non-null     float64
 11  Households broadband access                   34 non-null     float64
 12  Air quality (PM2.5)                           34 non-null     float64
 13  Life satisfaction                             34 non-null     float64
 14  Satisfaction with housing affordability       34 non-null     float64
 15  Internet speed                                34 non-null     float64
 16  Perceived social network support              34 non-null     float64
dtypes: float64(14), object(3)
memory usage: 4.8+ KB

In [16]:
oecd_clean = oecd_clean.drop(columns=['country' , 'countrycode'], axis =1)
oecd_clean

,Disposable income per capita,Employment rate,Unemployment rate,Homicide rate,Life expectancy,Population with at least secondary education,Number of rooms per capita,Mortality rate,Voter turnout,Households broadband access,Air quality (PM2.5),Life satisfaction,Satisfaction with housing affordability,Internet speed,Perceived social network support
0,39 872,76.3,4.1,0.9,83.0,15.3,2.3,3.0,89.8,86.1,8.5,7.1,41.6,-44.8,92.4
1,37 640,75.5,4.8,0.7,81.9,13.8,1.8,8.6,75.6,91.0,11.1,7.0,59.9,-42.5,89.8
2,35 487,62.8,5.8,1.4,82.3,17.2,2.1,8.6,90.7,94.6,11.8,6.9,59.3,-16.3,89.9
3,32 387,72.2,6.1,1.9,81.3,6.9,2.5,6.3,62.2,93.3,12.7,7.0,38.8,22.4,91.9
4,8 261,62.9,8.7,4.5,81.0,17.6,1.3,9.9,46.7,75.2,23.1,6.2,28.7,49.4,87.3
6,10 470,71.5,7.3,17.2,80.9,58.6,1.1,6.8,60.7,80.1,8.7,6.8,55.0,-41.0,33.2
7,26 092,75.1,2.3,1.5,79.9,5.7,1.5,10.2,65.4,92.8,13.0,6.8,50.7,-41.9,93.7
8,27 796,76.8,5.3,0.8,81.8,16.4,1.9,8.9,84.2,92.5,9.2,7.6,71.3,7.6,94.6
9,17 711,74.4,7.9,1.7,79.0,11.2,1.6,10.3,63.5,90.9,9.1,6.4,62.8,-46.7,93.6
10,28 154,72.2,9.4,1.1,81.6,11.1,1.8,9.0,66.8,95.5,7.1,7.8,75.2,-13.1,95.6
11,30 656,65.0,7.6,1.2,83.0,16.1,1.8,8.0,77.8,88.1,10.7,6.7,47.9,46.3,87.4
12,35 532,76.2,8.2,0.8,81.1,16.2,1.8,13.4,82.5,88.8,11.6,6.9,55.8,-34.9,89.1
13,20 931,70.9,12.9,0.7,81.8,17.9,1.3,9.1,53.7,85.0,11.1,5.9,40.4,-56.2,84.1
14,21 024,73.8,4.4,0.7,76.5,11.9,1.6,12.8,69.7,94.8,12.5,6.1,44.8,3.9,94.2
16,29 853,75.1,4.5,0.7,82.9,10.6,2.0,8.2,59.7,93.5,7.5,7.0,42.5,-9.2,91.6
17,15 120,69.7,3.7,1.5,82.6,12.4,1.2,7.5,68.5,74.3,20.6,7.3,29.7,27.7,93.5
18,31 920,61.9,7.5,0.6,83.4,33.3,1.5,7.9,63.9,84.1,15.8,6.4,56.3,-9.0,86.2
19,22 891,73.3,2.7,0.7,84.7,5.4,1.8,7.2,56.0,71.7,17.2,6.0,80.6,8.6,87.7
20,25 303,62.0,2.7,1.1,83.5,6.4,1.6,6.8,66.2,99.9,30.1,6.0,61.8,6.0,79.6
21,15 293,70.1,8.4,4.3,75.5,9.1,1.2,12.7,59.4,94.3,10.4,6.2,46.6,-29.0,91.9
22,17 929,72.5,6.8,2.6,77.4,5.6,1.6,11.4,52.2,90.4,9.8,6.6,45.9,-14.7,84.9
23,45 344,68.2,6.6,1.4,83.4,17.6,2.0,7.9,87.2,97.4,10.5,7.2,45.3,4.5,88.7
24,8 358,63.9,2.7,24.2,75.5,56.1,1.5,11.8,61.0,75.6,14.6,6.5,50.3,-54.0,82.2
25,31 827,84.3,3.9,0.6,81.9,19.2,2.1,8.9,81.6,98.6,12.1,7.4,41.2,13.9,92.7
27,32 368,77.4,3.7,0.7,83.1,16.3,2.3,8.1,77.1,98.6,6.8,7.4,55.4,-10.1,93.9
28,24 597,76.6,3.1,1.4,78.4,5.2,1.4,11.1,74.4,95.0,13.5,6.3,33.9,2.0,88.6
29,26 467,72.6,6.2,0.7,81.2,38.5,2.0,8.4,59.8,87.0,10.5,6.0,34.7,5.2,87.3
30,20 282,76.0,5.4,1.1,78.2,6.1,1.1,11.2,68.5,90.5,10.9,6.3,52.1,-27.0,93.8
31,27 250,73.1,3.7,0.3,82.0,11.0,1.6,8.7,53.6,94.0,13.5,6.7,28.5,-27.9,93.9
32,26 156,61.3,12.7,0.7,83.8,35.1,2.0,7.6,66.6,96.8,9.7,6.4,42.5,11.0,92.9
33,30 943,77.4,8.5,1.1,83.4,11.3,1.8,7.9,87.1,100.0,6.8,7.3,55.1,-14.1,93.5
34,64 469,83.9,4.2,0.6,84.3,13.8,1.8,7.3,45.1,98.1,12.5,7.3,59.6,29.7,92.2
36,33 222,78.5,3.6,0.9,80.7,17.8,2.0,9.2,60.3,99.8,9.2,6.8,46.2,-9.9,89.2
37,59 961,76.6,3.7,5.9,77.0,9.7,2.4,10.0,65.3,86.4,12.7,6.8,51.4,29.0,89.1

In [21]:
oecd_clean['Disposable income per capita'] = oecd_clean['Disposable income per capita'].str.replace(' ', '').astype(int)

In [22]:
oecd_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 34 entries, 0 to 37
Data columns (total 15 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Disposable income per capita                  34 non-null     int64
 1   Employment rate                               34 non-null     float64
 2   Unemployment rate                             34 non-null     float64
 3   Homicide rate                                 34 non-null     float64
 4   Life expectancy                               34 non-null     float64
 5   Population with at least secondary education  34 non-null     float64
 6   Number of rooms per capita                    34 non-null     float64
 7   Mortality rate                                34 non-null     float64
 8   Voter turnout                                 34 non-null     float64
 9   Households broadband access                   34 non-null     float64
 10  Air quality (PM2.5)                           34 non-null     float64
 11  Life satisfaction                             34 non-null     float64
 12  Satisfaction with housing affordability       34 non-null     float64
 13  Internet speed                                34 non-null     float64
 14  Perceived social network support              34 non-null     float64
dtypes: float64(14), int64(1)
memory usage: 4.2 KB

## K-Means

Perform [K-Means](https://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html) on the provided countries data set. You may include the full set of variables, or a subset of variables based on any of your initial data cleaning. 

Set the number of clusters to `4` and use the `n_init=20` parameter to evaluate 20 different random initializations of the model. 

After fitting the model, evaluate its classification on the full data set. You can extract these labels in two ways.

1. You can call the `.labels_` attribute of your fit model object
2. You can apply the `.predict()` method from your fit model object to the underlying data

Examine how the countries have been grouped among these clusters and comment on any patterns.


Note: Ensure that you do not try to pass the `ccode` or `country` variables to your fitting process as these variables are non-numeric.

In [23]:
oecd_clean_knn = KMeans(n_clusters = 4, random_state=422,
                # Number of times to randomly initialise and run the algorithm
                n_init=10
                )

# Fitting it to our data set
oecd_clean_knn = oecd_clean_knn.fit(oecd_clean)

oecd_clean_knn

c:\Users\Muhammad-\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1419: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(

KMeans(n_clusters=4, n_init=10, random_state=422)

## Different Values of K with the Elbow Method

Use the elbow method to identify an optimal number of clusters. To do this:

1. Fit a range of models with K-Means, using different values of `k` in each case. Use the `n_init=20` parameter to run the code for 20 different starting points. Consider a range of values of `k` from `2` to `20`
2. For each fitted model, save the `inertia` score from this model, which is a measure of the within cluster variance. This score can be accessed from the fit model with the `.inertia_` attribute
3. Create a plot of these inertia values against the number of identified clusters.

Evaluate your plot from Step 3 above and comment on the shape and any patterns. Based on this plot, what seems to be an appropriate number of clusters?

Fit a new model with this number of clusters and compare the groups to those identified above with `k=4`. How do the clusters compare in these two cases?

## Different Values of K with the Silhouette Score

An alternative way to score the performance of a clustering algorithm is via the [Silhouette Score](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.silhouette_score.html). A function to calculate this can be loaded with the following code:

```python
from sklearn.metrics import silhouette_score
```

The silhouette score is a measure of how _similar_ observations are, and thus higher values indicate more similar values, and potentially better clusters. Replicate your analysis from the elbow method above, this time trying a range of clusters from k=2 to k=20. For each model save the silhouette score. Which value of k produces the highest silhouette score?

Fit a new K-Means model with this value of k to your data where you have dropped measures of population. Are the clusters in this model materially different than your earlier clusters?

Note, the silhouette score takes as arguments the underlying data and the assigned labels from the model. The labels from the model can be extracted with the `.labels_` attribute.

## Clustering with HAC

Implement [AgglomerativeClustering](https://scikit-learn.org/stable/modules/generated/sklearn.cluster.AgglomerativeClustering.html) on this data. You can also review the user guide for this function [here](https://scikit-learn.org/stable/modules/clustering.html#hierarchical-clustering).

To do this, load the function with the following code:

```python
from sklearn.cluster import AgglomerativeClustering
```

Use the following hyperparameters to fit the model:

1. Set `distance_threshold=None` - this will allow the algorithm to fully merge all clusters
2. Set `n_clusters=4` - this will create four distinct clusters
3. Set `linkage='complete'` - this specifies the metric used to calculate the distance between clusters

How do the clusters identified here compare to those identified by K-Means?

## Building a Dendrogram - OPTIONAL

Refit your hierarchical model with the following parameters (if you choose to do so in sklearn).

1. Set `distance_threshold=0`
2. Set `n_clusters=None`
3. Set `linkage='ward'`

Build and display a dendrogram for this cluster analysis. Aim to include the country `ccode` variable as the label at the bottom of your dendrogram. There are several possible ways to do this, as sklearn does not have the easiest functionality to work with for creating a dendrogram. You may find it helpful to search on stack overflow. There are also further examples on.

1. [Plotly](https://plotly.com/python/dendrogram/)
2. [SciPy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.cluster.hierarchy.dendrogram.html)

Note, if using these alternative sources, they may fit the models with packages besides `sklearn`.

Looking at the dendrogram, does there appear to be any large jumps in the vertical distance where the distance between newly merged clusters quickly increases?

Note: I expect the process for generating this plot will require looking at examples outside of those presented in class. Your aim should be to use keyword searches to find useful code which you can modify to your purposes.